import React, { useState } from 'react';
import { Download, Trash2, Edit3, Plus, FileText } from 'lucide-react';

export default function AdaptiveReport() {
  const [reportTitle, setReportTitle] = useState('Clinical ML & Quantum Benchmarking Diagnostic Report');
  const [authorNotes, setAuthorNotes] = useState('Automated clinical inference synthesis generated by Q-Med Hybrid Platform.');
  const [reportItems, setReportItems] = useState([
    {
      id: 'item-1',
      title: 'Overall Benchmark Synthesis',
      type: 'text',
      content: 'Classical SVM and MLP achieve superior overall diagnostic accuracy (97.4%) on the Breast Cancer Wisconsin Diagnostic benchmark. Quantum QSVM achieves 85.1% accuracy on 4-qubit Hilbert space projections.',
      notes: 'Initial clinical assessment notes.'
    },
    {
      id: 'item-2',
      title: 'Radar Chart Comparison',
      type: 'figure',
      image: '/figures/benchmark/cancer_radar_chart.png',
      caption: 'Comparative 6-dimensional performance radar chart across Classical and Quantum models.'
    },
    {
      id: 'item-3',
      title: 'ROC Curve Benchmark',
      type: 'figure',
      image: '/figures/classical/cancer_roc_curves.png',
      caption: 'ROC Curves for Classical SVM variants demonstrating 0.996 AUC.'
    }
  ]);

  const [newItemTitle, setNewItemTitle] = useState('');
  const [newItemText, setNewItemText] = useState('');

  const handleAddItem = (e) => {
    e.preventDefault();
    if (!newItemTitle) return;
    const newItem = {
      id: `item-${Date.now()}`,
      title: newItemTitle,
      type: 'text',
      content: newItemText,
      notes: ''
    };
    setReportItems([...reportItems, newItem]);
    setNewItemTitle('');
    setNewItemText('');
  };

  const handleRemoveItem = (id) => {
    setReportItems(reportItems.filter(item => item.id !== id));
  };

  const handleNoteChange = (id, newNotes) => {
    setReportItems(reportItems.map(item => item.id === id ? { ...item, notes: newNotes } : item));
  };

  const handleDownloadReport = () => {
    let mdContent = `# ${reportTitle}\n\n`;
    mdContent += `**Generated Date:** ${new Date().toLocaleDateString()}\n\n`;
    mdContent += `## Author / Clinical Notes\n${authorNotes}\n\n---\n\n`;

    reportItems.forEach((item, index) => {
      mdContent += `### ${index + 1}. ${item.title}\n\n`;
      if (item.type === 'text') {
        mdContent += `${item.content}\n\n`;
      } else if (item.type === 'figure') {
        mdContent += `![${item.title}](${item.image})\n*${item.caption}*\n\n`;
      }
      if (item.notes) {
        mdContent += `> **Clinical Observation / Annotations:**\n> ${item.notes}\n\n`;
      }
      mdContent += `---\n\n`;
    });

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `adaptive_clinical_report_${Date.now()}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="section">
      <h2 className="section-title">📑 Adaptive Report Maker</h2>

      <div className="explainer">
        <div className="explainer-title">Interactive Live Report Synthesis</div>
        <p>
          Customized clinical and research report builder. Items can be dynamically added, edited, reordered, annotated with live typing rights, and downloaded as a publication-ready Markdown research report.
        </p>
      </div>

      {/* Action Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', margin: '20px 0', flexWrap: 'wrap', gap: '15px' }}>
        <input
          type="text"
          value={reportTitle}
          onChange={(e) => setReportTitle(e.target.value)}
          style={{
            fontSize: '1.4rem',
            fontWeight: 'bold',
            padding: '10px 15px',
            border: '2px solid #667eea',
            borderRadius: '8px',
            flex: 1,
            minWidth: '300px'
          }}
        />

        <button
          onClick={handleDownloadReport}
          className="btn-predict"
          style={{
            margin: 0,
            display: 'inline-flex',
            alignItems: 'center',
            gap: '8px',
            width: 'auto',
            background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)'
          }}
        >
          <Download size={18} /> Download Markdown Report
        </button>
      </div>

      {/* Author Notes Editor */}
      <div className="model-card">
        <label style={{ fontWeight: 600, color: '#4a5568', display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '8px' }}>
          <Edit3 size={16} /> Clinical Summary & Author Notes (Live Editable):
        </label>
        <textarea
          value={authorNotes}
          onChange={(e) => setAuthorNotes(e.target.value)}
          rows={3}
          style={{
            width: '100%',
            padding: '12px',
            border: '1px solid #cbd5e0',
            borderRadius: '6px',
            fontSize: '0.95rem',
            fontFamily: 'inherit'
          }}
        />
      </div>

      {/* Report Items List */}
      <h3 style={{ color: '#667eea', margin: '30px 0 15px 0', display: 'flex', alignItems: 'center', gap: '8px' }}>
        <FileText size={22} /> Live Report Sections ({reportItems.length} Blocks)
      </h3>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
        {reportItems.map((item, idx) => (
          <div key={item.id} className="model-card" style={{ position: 'relative', borderLeft: '5px solid #667eea' }}>
            {/* Delete button */}
            <button
              onClick={() => handleRemoveItem(item.id)}
              style={{
                position: 'absolute',
                top: '15px',
                right: '15px',
                background: '#fee2e2',
                border: 'none',
                color: '#dc2626',
                borderRadius: '6px',
                padding: '6px 10px',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '4px',
                fontSize: '0.85rem'
              }}
              title="Remove from report"
            >
              <Trash2 size={14} /> Remove
            </button>

            <h4 style={{ color: '#2d3748', fontSize: '1.2rem', marginBottom: '10px' }}>
              {idx + 1}. {item.title}
            </h4>

            {item.type === 'text' && (
              <p style={{ color: '#4a5568', lineHeight: '1.7', fontSize: '0.95rem' }}>{item.content}</p>
            )}

            {item.type === 'figure' && (
              <div style={{ margin: '15px 0', textAlign: 'center' }}>
                <img
                  src={item.image}
                  alt={item.title}
                  style={{ maxWidth: '100%', maxHeight: '350px', borderRadius: '8px', border: '1px solid #e2e8f0' }}
                />
                <div style={{ fontStyle: 'italic', fontSize: '0.85rem', color: '#718096', marginTop: '6px' }}>
                  {item.caption}
                </div>
              </div>
            )}

            {/* Note taking field */}
            <div style={{ marginTop: '15px', paddingTop: '12px', borderTop: '1px dashed #e2e8f0' }}>
              <label style={{ fontSize: '0.85rem', fontWeight: 600, color: '#667eea', display: 'block', marginBottom: '5px' }}>
                ✏️ Add Notes / Annotations for this Section:
              </label>
              <input
                type="text"
                placeholder="Type your notes or analysis here..."
                value={item.notes || ''}
                onChange={(e) => handleNoteChange(item.id, e.target.value)}
                style={{
                  width: '100%',
                  padding: '8px 12px',
                  border: '1px solid #cbd5e0',
                  borderRadius: '6px',
                  fontSize: '0.9rem'
                }}
              />
            </div>
          </div>
        ))}
      </div>

      {/* Add Custom Text Block Form */}
      <div className="model-card" style={{ marginTop: '30px', background: '#f8fafc', border: '2px dashed #cbd5e0' }}>
        <h4 style={{ color: '#2d3748', display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '15px' }}>
          <Plus size={18} /> Add Custom Section to Report
        </h4>
        <form onSubmit={handleAddItem}>
          <div className="form-group" style={{ marginBottom: '15px' }}>
            <label>Section Title:</label>
            <input
              type="text"
              placeholder="e.g., Clinical Recommendation / Methodology Critique"
              value={newItemTitle}
              onChange={(e) => setNewItemTitle(e.target.value)}
              required
            />
          </div>
          <div className="form-group" style={{ marginBottom: '15px' }}>
            <label>Content / Analysis:</label>
            <textarea
              rows={3}
              placeholder="Enter findings, mathematical proof, or clinical inferences..."
              value={newItemText}
              onChange={(e) => setNewItemText(e.target.value)}
              style={{
                width: '100%',
                padding: '10px',
                border: '1px solid #cbd5e0',
                borderRadius: '6px',
                fontFamily: 'inherit'
              }}
            />
          </div>
          <button type="submit" className="btn-predict" style={{ width: 'auto', padding: '10px 20px' }}>
            ➕ Append Section to Report
          </button>
        </form>
      </div>
    </div>
  );
}
