import React, { useState } from 'react';
import { Download, Trash2, Edit3, Plus, FileText } from 'lucide-react';

export default function AdaptiveReport() {
  const [reportTitle, setReportTitle] = useState('Clinical ML & Quantum Benchmarking Diagnostic Report');
  const [authorNotes, setAuthorNotes] = useState('Automated clinical inference synthesis generated by Q-Med Hybrid Platform.');
  const [reportItems, setReportItems] = useState([
    {
      id: 'item-1',
      title: 'Overall Benchmark Synthesis',
      type: 'text',
      content: 'Classical SVM and MLP achieve superior overall diagnostic accuracy (97.4%) on the Breast Cancer Wisconsin Diagnostic benchmark. Quantum QSVM achieves 85.1% accuracy on 4-qubit Hilbert space projections.',
      notes: 'Initial clinical assessment notes.'
    },
    {
      id: 'item-2',
      title: 'Radar Chart Comparison',
      type: 'figure',
      image: '/figures/benchmark/cancer_radar_chart.png',
      caption: 'Comparative 6-dimensional performance radar chart across Classical and Quantum models.'
    },
    {
      id: 'item-3',
      title: 'ROC Curve Benchmark',
      type: 'figure',
      image: '/figures/classical/cancer_roc_curves.png',
      caption: 'ROC Curves for Classical SVM variants demonstrating 0.996 AUC.'
    }
  ]);

  const [newItemTitle, setNewItemTitle] = useState('');
  const [newItemText, setNewItemText] = useState('');

  const handleAddItem = (e) => {
    e.preventDefault();
    if (!newItemTitle) return;
    const newItem = {
      id: `item-${Date.now()}`,
      title: newItemTitle,
      type: 'text',
      content: newItemText,
      notes: ''
    };
    setReportItems([...reportItems, newItem]);
    setNewItemTitle('');
    setNewItemText('');
  };

  const handleRemoveItem = (id) => {
    setReportItems(reportItems.filter(item => item.id !== id));
  };

  const handleNoteChange = (id, newNotes) => {
    setReportItems(reportItems.map(item => item.id === id ? { ...item, notes: newNotes } : item));
  };

  const handleDownloadReport = () => {
    let mdContent = `# ${reportTitle}\n\n`;
    mdContent += `**Generated Date:** ${new Date().toLocaleDateString()}\n\n`;
    mdContent += `## Author / Clinical Notes\n${authorNotes}\n\n---\n\n`;

    reportItems.forEach((item, index) => {
      mdContent += `### ${index + 1}. ${item.title}\n\n`;
      if (item.type === 'text') {
        mdContent += `${item.content}\n\n`;
      } else if (item.type === 'figure') {
        mdContent += `![${item.title}](${item.image})\n*${item.caption}*\n\n`;
      }
      if (item.notes) {
        mdContent += `> **Clinical Observation / Annotations:**\n> ${item.notes}\n\n`;
      }
      mdContent += `---\n\n`;
    });

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `adaptive_clinical_report_${Date.now()}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="hub-section active">
      <div className="section-header">
        <div>
          <h1 style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <FileText size={24} style={{ color: 'var(--classical-color)' }} />
            Adaptive Report Builder
          </h1>
          <p className="subtitle">
            Customizable publication-ready Markdown report synthesizer. Dynamically annotate live findings, attach saved figure cards, and export full reports.
          </p>
        </div>
      </div>

      {/* Action Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', margin: '0 0 24px 0', flexWrap: 'wrap', gap: '16px' }}>
        <input
          type="text"
          value={reportTitle}
          onChange={(e) => setReportTitle(e.target.value)}
          className="form-group"
          style={{
            fontSize: '1.1rem',
            fontWeight: '600',
            padding: '10px 14px',
            background: '#FFFFFF',
            border: '1px solid var(--border-color)',
            borderRadius: '8px',
            color: 'var(--text-primary)',
            flex: 1,
            minWidth: '320px',
            outline: 'none'
          }}
        />

        <button
          onClick={handleDownloadReport}
          className="btn btn-primary"
          style={{ padding: '10px 20px' }}
        >
          <Download size={16} /> Export Markdown Report
        </button>
      </div>

      {/* Author Notes Editor */}
      <div className="card" style={{ marginBottom: '24px' }}>
        <label style={{ fontWeight: 600, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px', fontSize: '0.875rem' }}>
          <Edit3 size={16} style={{ color: 'var(--classical-color)' }} /> Author & Clinical Notes (Live Editable):
        </label>
        <textarea
          value={authorNotes}
          onChange={(e) => setAuthorNotes(e.target.value)}
          rows={3}
          style={{
            width: '100%',
            padding: '10px 12px',
            background: '#FFFFFF',
            border: '1px solid var(--border-color)',
            borderRadius: '6px',
            fontSize: '0.875rem',
            color: 'var(--text-primary)',
            fontFamily: 'inherit',
            outline: 'none'
          }}
        />
      </div>

      {/* Report Items List */}
      <h3 style={{ color: 'var(--text-primary)', margin: '0 0 16px 0', display: 'flex', alignItems: 'center', gap: '8px', fontSize: '1.1rem' }}>
        <FileText size={18} style={{ color: 'var(--classical-color)' }} /> Live Report Sections ({reportItems.length} Blocks)
      </h3>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        {reportItems.map((item, idx) => (
          <div key={item.id} className="card" style={{ position: 'relative' }}>
            {/* Delete button */}
            <button
              onClick={() => handleRemoveItem(item.id)}
              className="btn btn-sm btn-outline-danger"
              style={{
                position: 'absolute',
                top: '24px',
                right: '24px'
              }}
              title="Remove block"
            >
              <Trash2 size={14} /> Remove
            </button>

            <h4 style={{ color: 'var(--text-primary)', fontSize: '1rem', marginBottom: '10px', fontWeight: 600 }}>
              {idx + 1}. {item.title}
            </h4>

            {item.type === 'text' && (
              <p style={{ color: 'var(--text-secondary)', lineHeight: '1.6', fontSize: '0.875rem' }}>{item.content}</p>
            )}

            {item.type === 'figure' && (
              <div style={{ margin: '14px 0', textAlign: 'center' }}>
                <div style={{ background: '#FFFFFF', padding: '10px', borderRadius: '8px', border: '1px solid var(--border-color)', display: 'inline-block', maxWidth: '100%' }}>
                  <img
                    src={item.image}
                    alt={item.title}
                    style={{ maxWidth: '100%', maxHeight: '350px', borderRadius: '6px' }}
                  />
                </div>
                <div style={{ fontStyle: 'italic', fontSize: '0.82rem', color: 'var(--text-secondary)', marginTop: '8px' }}>
                  {item.caption}
                </div>
              </div>
            )}

            {/* Note taking field */}
            <div style={{ marginTop: '14px', paddingTop: '12px', borderTop: '1px solid var(--border-color)' }}>
              <label style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: '6px' }}>
                Section Annotations:
              </label>
              <input
                type="text"
                placeholder="Type your notes or clinical observations here..."
                value={item.notes || ''}
                onChange={(e) => handleNoteChange(item.id, e.target.value)}
                style={{
                  width: '100%',
                  padding: '8px 12px',
                  background: '#FFFFFF',
                  border: '1px solid var(--border-color)',
                  borderRadius: '6px',
                  color: 'var(--text-primary)',
                  fontSize: '0.85rem',
                  outline: 'none'
                }}
              />
            </div>
          </div>
        ))}
      </div>

      {/* Add Custom Text Block Form */}
      <div className="card" style={{ marginTop: '28px', border: '1px dashed var(--border-color)' }}>
        <h4 style={{ color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px', fontSize: '0.95rem', fontWeight: 600 }}>
          <Plus size={16} style={{ color: 'var(--classical-color)' }} /> Append Custom Section
        </h4>
        <form onSubmit={handleAddItem}>
          <div className="form-group" style={{ marginBottom: '14px' }}>
            <label style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginBottom: '4px', display: 'block' }}>Section Title:</label>
            <input
              type="text"
              placeholder="e.g., Clinical Recommendation / Quantum Advantage Verdict"
              value={newItemTitle}
              onChange={(e) => setNewItemTitle(e.target.value)}
              required
              style={{
                width: '100%',
                padding: '8px 12px',
                background: '#FFFFFF',
                border: '1px solid var(--border-color)',
                borderRadius: '6px',
                color: 'var(--text-primary)',
                outline: 'none'
              }}
            />
          </div>
          <div className="form-group" style={{ marginBottom: '16px' }}>
            <label style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginBottom: '4px', display: 'block' }}>Content / Observations:</label>
            <textarea
              rows={3}
              placeholder="Enter details, findings, or annotations..."
              value={newItemText}
              onChange={(e) => setNewItemText(e.target.value)}
              style={{
                width: '100%',
                padding: '8px 12px',
                background: '#FFFFFF',
                border: '1px solid var(--border-color)',
                borderRadius: '6px',
                color: 'var(--text-primary)',
                fontFamily: 'inherit',
                outline: 'none'
              }}
            />
          </div>
          <button type="submit" className="btn btn-outline" style={{ display: 'inline-flex', alignItems: 'center', gap: '6px' }}>
            <Plus size={16} /> Append Section to Report
          </button>
        </form>
      </div>
    </div>
  );
}
